{
 "title": "Uptime Kuma - SLA/Latency/Certs",
 "description": "A dashboard to visualize the metrics from HTTP endpoints in [Uptime Kuma](https://github.com/louislam/uptime-kuma)\r\n\r\nImproved by https://github.com/EliottGoye",
 "tags": [ "uptime-kuma" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "query": {
     "query": "label_values(monitor_response_time, monitor_type)"
    }
   },
   {
    "name": "monitor",
    "query": {
     "query": "label_values(monitor_response_time{monitor_type=~\"$type\"}, monitor_name)"
    }
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Online Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Offline Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status == 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average response time (15m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (2h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (24h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(0*(monitor_status{monitor_name=~\"$monitor\"}!=1)) or (monitor_status{monitor_name=~\"$monitor\"}*100)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  { "title": "$monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "monitor" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"$monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(0*(monitor_status{monitor_name=~\"$monitor\"}!=1)) or (monitor_status{monitor_name=~\"$monitor\"}*100)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_response_time{monitor_name=~\"$monitor\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "avg_over_time(monitor_response_time{monitor_name=~\"$monitor\"}[24h])",
     "legendFormat": "AVG 24H"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "monitor_response_time{monitor_name=~\"$monitor\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Certificate days until expire",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_cert_days_remaining{monitor_name=~\"$monitor\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Certificate Valid",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_cert_is_valid{monitor_name=~\"$monitor\"}",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}