{
 "title": "Media Dashboard",
 "tags": [
  "sonarr",
  "readarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "sabnzbd",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "prowlarr_instance",
    "label": "Prowlarr Instance",
    "query": {
     "query": "label_values({__name__=~\"prowlarr_.*\"},job)"
    }
   },
   {
    "name": "sabnzbd_instance",
    "label": "SABnzbd Instance",
    "query": {
     "query": "label_values({__name__=~\"sabnzbd_.*\"},job)"
    }
   },
   {
    "name": "radarr_instance",
    "label": "Radarr Instance",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"},job)"
    }
   },
   {
    "name": "sonarr_instance",
    "label": "Sonarr Instance",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prowlarr - ${prowlarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "prowlarr_instance"
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_system_status{job=~\"${prowlarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"prowlarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues{job=~\"${prowlarr_instance}\"})",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total{job=~\"${prowlarr_instance}\"})",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total{job=~\"${prowlarr_instance}\"} - prowlarr_indexer_enabled_total{job=~\"${prowlarr_instance}\"})",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{job=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{job=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{job=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms{job=~\"${prowlarr_instance}\"})",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{job=~\"${prowlarr_instance}\"}[$__range])) / sum(prowlarr_indexer_queries_total{job=~\"${prowlarr_instance}\"})",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(prowlarr_indexer_vip_expires_in_seconds)",
     "legendFormat": "Nearest VIP Expiration"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "prowlarr_indexer_average_response_time_ms{job=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(prowlarr_user_agent_queries_total{job=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{job=~\"${prowlarr_instance}\"}[$__range])) by (indexer)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{job=~\"${prowlarr_instance}\"}[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total{job=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total{job=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP Expiration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "prowlarr_indexer_vip_expires_in_seconds{job=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() * 1000) + (prowlarr_indexer_vip_expires_in_seconds{job=~\"${prowlarr_instance}\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "prowlarr_system_health_issues{job=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Radarr - ${radarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "radarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_system_status{job=~\"${radarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"$radarr_instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_downloaded_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_movie_monitored_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "radarr_movie_wanted_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_queue_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "radarr_movie_downloaded_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_history_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "radarr_movie_filesize_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "radarr_rootfolder_freespace_bytes{job=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_quality_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"cadvisor\", name=\"$radarr_instance\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"cadvisor\", name=\"$radarr_instance\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{job=~\"${radarr_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "radarr_system_health_issues{job=\"${radarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sonarr - ${sonarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }, "repeat": "sonarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_system_status{job=~\"${sonarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"$sonarr_instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total{job=~\"${sonarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "sonarr_history_total{job=~\"${sonarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "sonarr_episode_downloaded_total{job=~\"${sonarr_instance}\"}",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_series_monitored_total{job=~\"${sonarr_instance}\"})",
     "legendFormat": "Series Monitored"
    },
    {
     "expr": "max(sonarr_series_total{job=~\"${sonarr_instance}\"})",
     "legendFormat": "Series Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_season_monitored_total{job=~\"${sonarr_instance}\"})",
     "legendFormat": "Seasons Monitored"
    },
    {
     "expr": "max(sonarr_season_total{job=~\"${sonarr_instance}\"})",
     "legendFormat": "Seasons Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_episode_missing_total{job=~\"${sonarr_instance}\"})",
     "legendFormat": "Episodes Missing"
    },
    {
     "expr": "max(sonarr_episode_total{job=~\"${sonarr_instance}\"})",
     "legendFormat": "Episodes Total"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_quality_total{job=~\"${sonarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"cadvisor\", name=\"$sonarr_instance\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"cadvisor\", name=\"$sonarr_instance\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sonarr_series_filesize_bytes{job=~\"${sonarr_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 93 },
   "targets": [
    {
     "expr": "sonarr_system_health_issues{job=~\"${sonarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SABnzbd - ${sabnzbd_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }, "repeat": "sabnzbd_instance" },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sabnzbd_downloaded_bytes{job=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Lifetime"
    },
    {
     "expr": "max(increase(sabnzbd_downloaded_bytes{job=~\"${sabnzbd_instance}\"}[$__range]))",
     "legendFormat": "Recent"
    },
    {
     "expr": "sabnzbd_queue_length{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "sabnzbd_total_bytes{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Queue Size"
    },
    {
     "expr": "sabnzbd_remaining_bytes{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Remaining"
    },
    {
     "expr": "sum(sabnzbd_server_articles_success{job=~\"${sabnzbd_instance}\"}) / sum(sabnzbd_server_articles_total{job=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_quota_bytes{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "1 - max(sabnzbd_remaining_quota_bytes{job=~\"${sabnzbd_instance}\"} / sabnzbd_quota_bytes{job=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sabnzbd_remaining_quota_bytes{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_article_cache_articles{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Articles"
    },
    {
     "expr": "sabnzbd_article_cache_bytes{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  }
 ]
}