name: renovate-config-validator

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    paths:
      - "renovate.json"
  pull_request:
    paths:
      - "renovate.json"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b850926b611b1f3d3fe3729776339c217834bf2c # v2.2.0
